#! /bin/sh
 
### BEGIN INIT INFO
# Provides:          groundcontrol
# Required-Start:    $local_fs $network $remote_fs
# Required-Stop:     $local_fs $network $remote_fs
# Should-Start:      $NetworkManager
# Should-Stop:       $NetworkManager
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO
 
. /lib/lsb/init-functions
 
name="groundcontrol"
gc_home="/opt/groundcontrol"
gc_bin="$gc_home/groundcontrol"
gc_conf="/etc/groundcontrol.json"
pid_file="/var/run/$name.pid"
 
start () {
	command="${gc_bin} -- -config ${gc_conf}"
	log_daemon_msg "Starting $name"
	if start-stop-daemon --start --quiet --oknodo -d $gc_home --pidfile "$pid_file" -b -m --exec $command; then
		log_end_msg 0
	else
		log_end_msg 1
	fi
}
 
stop () {
	start-stop-daemon --stop --quiet --oknodo --pidfile "$pid_file"
}
 
status () {
	status_of_proc -p $pid_file "" "$name"
}
 
case $1 in
	start)
		if status; then exit 0; fi
		start
		;;
	stop)
		stop
		;;
	reload)
		stop
		start
		;;
	restart)
		stop
		start
		;;
	status)
		status && exit 0 || exit $?
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload|status}"
		exit 1
		;;
esac
 
exit 0
